#!/usr/bin/env python3
# midi2c.py — transcode a Standard MIDI File into a C header (packed note-event
# stream) that the spike_midi_dexed sequencer plays through Dexed.
#
# Usage:
#   python tools/midi2c.py [input.mid] [output.h]
# Defaults:
#   input  = assets/William Tell Overture.mid   (relative to project root)
#   output = src/william_tell_mid.h
#
# Merges all tracks, honors the tempo map (Set-Tempo meta events), and emits
# {uint16 deltaMs, uint8 note, uint8 vel} rows (vel 0 = note-off; note 0 = rest
# padding for deltas > 60000ms). Assumes a positive (ticks-per-quarter) division.

import struct, sys, os

root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
inp = sys.argv[1] if len(sys.argv) > 1 else os.path.join(root, "assets", "William Tell Overture.mid")
out = sys.argv[2] if len(sys.argv) > 2 else os.path.join(root, "src", "william_tell_mid.h")

data = open(inp, "rb").read()

def rd_varlen(b, i):
    v = 0
    while True:
        c = b[i]; i += 1
        v = (v << 7) | (c & 0x7F)
        if not (c & 0x80): break
    return v, i

assert data[:4] == b"MThd", "not a MIDI file"
_, fmt, ntrks, division = struct.unpack(">IHHH", data[4:14])
tpq = division
pos = 14
tracks = []
for t in range(ntrks):
    assert data[pos:pos+4] == b"MTrk", f"bad track {t} @ {pos}"
    length = struct.unpack(">I", data[pos+4:pos+8])[0]
    tracks.append((pos+8, pos+8+length))
    pos = pos + 8 + length

tempo_events = []   # (abs_tick, us_per_quarter)
all_notes = []      # (abs_tick, on, note, vel)
for (s, e) in tracks:
    i = s; tick = 0; status = None
    while i < e:
        dt, i = rd_varlen(data, i); tick += dt
        b0 = data[i]
        if b0 & 0x80:
            status = b0; i += 1
        if status is None:
            break
        hi = status & 0xF0
        if status == 0xFF:
            meta = data[i]; i += 1
            ln, i = rd_varlen(data, i)
            payload = data[i:i+ln]; i += ln
            if meta == 0x51 and ln == 3:
                tempo_events.append((tick, (payload[0] << 16) | (payload[1] << 8) | payload[2]))
        elif status in (0xF0, 0xF7):
            ln, i = rd_varlen(data, i); i += ln
        elif hi in (0x80, 0x90, 0xA0, 0xB0, 0xE0):
            d1 = data[i]; d2 = data[i+1]; i += 2
            if hi == 0x90:   all_notes.append((tick, d2 > 0, d1, d2))
            elif hi == 0x80: all_notes.append((tick, False, d1, 0))
        elif hi in (0xC0, 0xD0):
            i += 1
        else:
            i += 1

tempo_events.sort()
if not tempo_events:
    tempo_events = [(0, 500000)]

def tick_to_ms(t):
    ms = 0.0; last_tick = 0; uspq = tempo_events[0][1]
    for (tt, uu) in tempo_events:
        if tt >= t: break
        ms += (tt - last_tick) * (uspq / tpq) / 1000.0
        last_tick = tt; uspq = uu
    ms += (t - last_tick) * (uspq / tpq) / 1000.0
    return ms

all_notes.sort(key=lambda x: x[0])
events = sorted(((tick_to_ms(tk), on, n, v) for (tk, on, n, v) in all_notes), key=lambda x: x[0])
note_ons = [e for e in events if e[1]]
dur = events[-1][0] if events else 0
poly = 0; cur = 0
for (_, on, _, _) in events:
    cur = cur + 1 if on else max(0, cur - 1)
    poly = max(poly, cur)

out_rows = []
prev_ms = 0
for (ms, on, note, vel) in events:
    absr = int(round(ms)); d = absr - prev_ms; prev_ms = absr
    while d > 60000:
        out_rows.append((60000, 0, 0)); d -= 60000
    out_rows.append((d, note, vel if on else 0))

print(f"format={fmt} ntrks={ntrks} tpq={tpq} tempos={len(tempo_events)} "
      f"events={len(out_rows)} noteOns={len(note_ons)} maxPoly={poly} dur={dur/1000:.0f}s")

with open(out, "w") as f:
    f.write("// william_tell_mid.h - GENERATED by tools/midi2c.py. Do not edit by hand.\n")
    f.write("// Packed note event stream for the Dexed sequencer in main.cpp.\n")
    f.write("// {deltaMs since prev event, note, vel}  vel 0 = note-off.\n")
    f.write("#pragma once\n#include <stdint.h>\n\n")
    f.write("struct SongEv { uint16_t dms; uint8_t note; uint8_t vel; };\n\n")
    f.write(f"// {len(out_rows)} events, {dur/1000:.0f}s, notes "
            f"{min(n[2] for n in note_ons)}..{max(n[2] for n in note_ons)}, maxPoly {poly}\n")
    f.write("static const SongEv kWilliamTellSong[] = {\n")
    for k in range(0, len(out_rows), 8):
        f.write("  " + " ".join(f"{{{d},{n},{v}}}," for (d, n, v) in out_rows[k:k+8]) + "\n")
    f.write("};\n")
print(f"wrote {out}")
